services:
  app:
    # Build locally, or use pre-built image on VPS
    build:
      context: .
      dockerfile: Dockerfile
    image: csodaszarvas:local
    container_name: csodaszarvas-local
    restart: unless-stopped
    ports:
      - "3003:3000" # External port 3002, internal port 3000
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    networks:
      - csodaszarvas-local-network

networks:
  csodaszarvas-local-network:
    driver: bridge
