version: "23.8"

services:
  app:
    # Build locally, or use pre-built image on VPS
    build:
      context: .
      dockerfile: Dockerfile
    image: csodaszarvas:test
    container_name: csodaszarvas-test
    restart: unless-stopped
    ports:
      - "3002:3000" # External port 3002, internal port 3000
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    networks:
      - csodaszarvas-test-network

networks:
  csodaszarvas-network:
    driver: bridge
